### ISSUE TITLE
'bachmode' in deploy.sh

### ISSUE THREAD

**Issue by gal20040** [dilmerv/UnityBuildPipelines#1]
Hi Dilmer!

You used 'bachmode' in https://github.com/dilmerv/UnityBuildPipelines/blob/master/BuildScripts/deploy.sh

Did you mean 'batchmode'?

**Comment by dilmerv** [comment]
I did thank you I will fix this.

**Comment by dilmerv** [comment]
This was now corrected in my latest commit thanks.
